server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/order_service_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
